repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-yaml
      - id: check-toml
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: requirements-txt-fixer
      - id: detect-private-key
      - id: sort-simple-yaml
  - repo: https://github.com/asottile/pyupgrade
    rev: v3.3.1
    hooks:
      - id: pyupgrade
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: "v2.7.1"
    hooks:
      - id: prettier
  - repo: local
    hooks:
      - id: autoflake
        name: autoflake
        entry: autoflake
        language: python
        types: [python]
        args:
          [
            --in-place,
            --remove-all-unused-imports,
            --remove-unused-variable,
            --ignore-init-module-imports,
          ]
      - id: isort
        name: isort
        entry: isort
        language: python
        types: [python]
      - id: black
        name: black
        entry: black
        language: python
        types: [python]
        args: [--quiet]
      - id: flake8
        name: flake8
        entry: flake8
        language: python
        types: [python]
      - id: mypy
        name: mypy
        entry: mypy
        language: python
        types: [python]
