[tool.black]
include = '\.pyi?$'
line-length = 120
target-version = ['py39']

[tool.coverage.report]
exclude_lines = [
  "pragma: no cover",
  "def __repr__",
  "def __str__",
  "raise AssertionError",
  "raise NotImplementedError",
  "if __name__ == .__main__.:",
  "if TYPE_CHECKING:",
  "if typing.TYPE_CHECKING:",
]

[tool.coverage.run]
branch = true
omit = ["tests/fixtures/*"]
source = ["src", "tests"]

[tool.isort]
profile = "black"

[tool.pytest.ini_options]
addopts = "-ra -v --durations=5 --cov=src"
